// Content for Stanza II — Minimal Surfaces, transcribed from
// scrollytelling-catenoid-narrative-copy.md. Kept as plain data, not
// markup, mirroring narrative.js's convention (viz/src/lib/content/narrative.js)
// so copy can be revised without touching the page.
//
// Order here is doc order with Slides 4 and 5 swapped (defining property
// before "one solution becomes a field") — approved narrative change: the
// zero-mean-curvature property should be established before saying it
// produces an infinite family, rather than after.
//
// Each body paragraph starting with "> " renders as a blockquote. **bold**
// renders inline (see renderInline in the page). `visualLabel` /
// `visualNote` describe what VisualPlaceholder.svelte should show for
// slides without a built visual yet; the Euler's-question slide (id
// 'euler-question') has none because its visual is the live catenoid
// interactive instead.
//
// 'euler-question' has two extra fields the other slides don't: `stages`
// is the cinch/curve/catenary sandbox's own copy — `prompt` scrolls in
// (same as `body`, just in its own nested sequence, see the page's nested
// <Scrolly>), `caption` is stationary text shown next to the drag control
// once that stage is reached. `body` here is the reveal-phase narrative
// that plays alongside the cylinder sweeping open, before the sandbox
// appears.

export const slides = [
	{
		id: 'intro',
		title: 'Minimal Surfaces',
		// The epigraph paragraph (starting with "> ") renders as a blockquote
		// styled the same as Stanza I's opening -- see splitQuote/.epigraph in
		// +page.svelte. Split at " - " (not the rendered em dash) so splitQuote
		// can find the attribution, same convention as nonEuclideanGeometry.js.
		body: [
			"Leonhard Euler, an 18th century mathematician (and also a physicist, astronomer, logician, geographer, music theorist and engineer!) is one of the many characters in *Poetry of the Universe*.",
			'> "Euler\'s mathematical interests ranged from the purest theoretical observations to the most practical applied problems." - Robert Osserman, *Poetry of the Universe*',
			'His presence in the book revolves around his mathematical proof that distortion is inevitable when representing a curved world on a flat map.',
			"A different question Euler solved would turn out to be a first major discovery in what would eventually become my father's field: Minimal Surfaces."
		],
		visualLabel: 'Transition motif from Stanza I'
	},
	{
		id: 'euler-question',
		title: 'Connecting two rings',
		body: [
			"In the 1740's, Leonhard Euler worked on a deceptively simple question:",
			'> What surface connects two rings using the least possible area?',
			'A natural starting point would be rotating a straight line around the rings to make a cylinder.'
		],
		stages: [
			{
				prompt: 'But we can do better if we cinch the middle.',
				caption: 'Drag the point up and down.'
			},
			{
				prompt: 'What if the transition were smooth instead of sharp?',
				caption: 'Drag the second point sideways to soften the curve.'
			},
			{
				prompt:
					"In 1744, Leonhard Euler identified the optimal curve that produces the smallest possible surface.",
				caption: 'The optimal curve.'
			}
		]
		// Visual: the live catenoid interactive, rendered directly by this page.
	},
	{
		id: 'euler-answer',
		title: 'The Catenoid',
		body: [
			'Euler found the answer comes from rotating a familiar curve.',
			'The curve is called the **catenary**, from the Latin catena ("chain"), because it is the shape naturally formed by a freely hanging chain.',
			'Euler called the shape generated by rotating it the **catenoid**, which turned out to be the first identified minimal surface (other than a plane).'
		],
		visualLabel: 'Chain animation'
	},
	{
		id: 'defining-property',
		title: 'The special curvature of the Catenoid',
		// `stages` replaces `body` for this slide — each prompt is shown in
		// the sticky panel in turn as the reader scrolls through
		// MeanCurvatureScene's own five animation beats (see
		// MEAN_CURVATURE_STAGES / curvatureStageIndex in +page.svelte),
		// rather than sitting as one static block for the whole animation.
		stages: [
			{ prompt: "In the decades that followed, it was proven that the catenoid has a very interesting property. Let's zoom into a single point on its surface." },
			{ prompt: 'Around the point on top of the catenoid, there are two curves that reveal how the surface bends -- one bends along the **catenary curve**, and the other around the **rotational curve**.' },
			{ prompt: 'Isolated from the surface, we can see **two curves bend in opposite directions**. This means it has **negative Gaussian curvature** as described in the previous Stanza.' },
			{ prompt: 'But these two curves have another special property.' },
			{ prompt: 'They have the exact same amount of curvature, but in opposite directions. This feature, defined as a **mean curvature of zero** is true not just at this point, but at all points on the surface of the catenoid... And more strikingly **at all points of every smooth minimal surface**.' }
		]
		// Visual: MeanCurvatureScene, rendered directly by this page (see
		// the scene-panel branch for curvatureIndex in +page.svelte).
	},
	{
		id: 'surface-explorer',
		title: 'One equation, many surfaces',
		// A subsequent slide for now, not a replacement for 'field-grows'
		// above -- see MinimalSurfaceExplorer.svelte for the interactive
		// itself (family dropdown + parameter slider, user-driven via
		// OrbitControls rather than scroll-scrubbed). Once this pattern is
		// confirmed to work well, 'field-grows' above is the likely home
		// for it long-term.
		body: [
			'Choose a family from the dropdown, and drag the slider to see how a single mathematical description can describe many different-looking surfaces.',
			'The **catenoid and the helicoid** (a spiral shape) are two shapes that do not look alike — but they turn out to be the same family, with a single parameter to transition between them.',
			"The **Enneper surface** is a single surface, but takes on surprisingly different character dependning on how much of it you view. It also shows how these surfaces can intersect themselves.",
			'And the **Scherk surface** shows a first family of "periodic" - or endlessly repeating surfaces.',
		],
		visualLabel: 'Minimal surface family explorer'
	},
	/*
	{
		id: 'field-grows',
		title: 'An explosion of surfaces',
		body: [
			'Over the following century, mathematicians continue to study these surfaces, but defining new surfaces was hampered by needing solving an impractically different set of equations.',
			"Weierstrass, building on Riemann's methods changed that. Using complex numbers (the sum of a real and imaginary number) they developed a way to define an infinite family of minimal surfaces.",
			'This new approach helped transform isolated examples into a coherent field of geometry.'
		],
		visualLabel: 'Gallery of minimal surfaces (Riemann’s family)'
	},*/ 
	{
		id: 'two-centuries',
		title: 'The Field Keeps Growing',
		body: [
			'Throughout the nineteenth and twentieth centuries, mathematicians discovered new minimal surfaces, developed general methods for constructing and classifying them, and explored when they exist and when they remain stable.',
			'By 1969, enough of that work had accumulated for Robert Osserman to bring much of the subject together in a graduate-level textbook: *A Survey of Minimal Surfaces*.',
			'Just one year later, NASA researcher Alan Schoen described a remarkable new family of **triply periodic minimal surfaces**, including the **gyroid**. Developed within an engineering research environment, these surfaces would later become some of the most influential geometries outside mathematics.',
			"Using the citations of Osserman's textbook, the next section follows the journey of minimal surfaces -- from 200 years of theoretical math to applications in fields ranging from materials science and biology to computer graphics, computer vision and theoretical physics."
		]
		// This is now the outro (see .cover-section in +page.svelte) — no
		// visualLabel, it doesn't sit in the scene-panel flow the slides
		// before it use.
	},
/*	{
		id: 'transition',
		title: 'Beyond Mathematics',
		body: [
			'For more than two centuries, minimal surfaces grew primarily as a branch of pure mathematics.',
			'Then researchers in fields ranging from materials science and biology to computer graphics, computer vision and theoretical physics began recognizing these same geometries in their own work.',
			'The next stanza follows that journey through the citation history of *A Survey of Minimal Surfaces*.'
		],
		visualLabel: 'Preview of the citation network (Stanza III)'
	}*/
];

// A third narrative space, alongside the sidebar (title + sticky prompts,
// paired to a scene) and each scene's own progress-driven text: a few
// sentences of connective prose that stand on their own, for a beat that
// doesn't need a built visual and isn't tied to any scene's timeline. Same
// component and convention as nonEuclideanGeometry.js's own interstitials
// (see $lib/components/Interstitial.svelte) -- ridden as a card, not pinned.
//
// 'soap-film' and 'field-grows' used to be generic slides (VisualPlaceholder
// fallback) sitting between 'defining-property' and 'surface-explorer' -- see
// +page.svelte for where they now sit, both as standalone cards between the
// same two <main>s, one after the other with no visual between them yet (a
// visual for that gap is a possible future addition -- see the page's own
// comment on the split). 'soap-film's body previously carried two overlapping
// drafts of the same Plateau story; consolidated to one pass here rather than
// moved over verbatim. 'field-grows' carried a retired draft as a block
// comment, dropped here rather than kept alongside the live text.
export const interstitials = [
	{
		id: 'soap-film',
		body: [
			'Minimal surfaces are **mathematical objects**. But researchers have often used **natural models** — specifically soap films — to understand them.',
			"It was already known in the eighteenth century that soap films naturally minimize their area, but producing stable, repeatable experiments was much harder than making bubbles for amusement.",
			"In the 1840s, a hundred years after Euler's proof, physicist Joseph Plateau developed a stable enough soap film mixture to systematically study how they form around wire frames.",
			'By pulling apart two rings dipped in soap, he made the first known stable catenoid — the shape Euler had described a century before. Observation had caught up with theory.'
		]
	},
	{
		id: 'field-grows',
		body: [
			'In the hundred years it took to fabricate a stable catenoid from soap film, mathematicians were hard at work to calculate what other minimal surfaces existed.',
			'In the 1760s, Joseph-Louis Lagrange derived an equation that certain classes of minimal surfaces must satisfy. But finding solutions was extraordinarily difficult, and for decades only a handful of examples were known.',
			'In the 1860s, that began to change. Work by Weierstrass, Enneper, Riemann and others brought tools from the emerging field of complex analysis (a technique using functions that combine real and imaginary numbers) into the study of minimal surfaces.',
			'These new approaches opened the door to whole families of surfaces — including some that could never appear as stable soap films.'
		]
	}
];
