// Content for Stanza II — Minimal Surfaces, transcribed from
// scrollytelling-catenoid-narrative-copy.md. Kept as plain data, not
// markup, mirroring narrative.js's convention (viz/src/lib/content/narrative.js)
// so copy can be revised without touching the page.
//
// Order here is doc order with Slides 4 and 5 swapped (defining property
// before "one solution becomes a field") — approved narrative change: the
// zero-mean-curvature property should be established before saying it
// produces an infinite family, rather than after.
//
// Each body paragraph starting with "> " renders as a blockquote. **bold**
// renders inline (see renderInline in the page). `visualLabel` /
// `visualNote` describe what VisualPlaceholder.svelte should show for
// slides without a built visual yet; the Euler's-question slide (id
// 'euler-question') has none because its visual is the live catenoid
// interactive instead.
//
// 'euler-question' has two extra fields the other slides don't: `stages`
// is the cinch/curve/catenary sandbox's own copy — `prompt` scrolls in
// (same as `body`, just in its own nested sequence, see the page's nested
// <Scrolly>), `caption` is stationary text shown next to the drag control
// once that stage is reached. `body` here is the reveal-phase narrative
// that plays alongside the cylinder sweeping open, before the sandbox
// appears.

export const slides = [
	{
		id: 'intro',
		title: 'Minimal Surfaces',
		body: [
			'Our last stanza ended with hyperbolic geometry -- a field foundational for understanding what is meant by curved space.',
			'This geometry also underpins the branch of mathematics that Osserman dedicated his career to: **minimal surfaces**.',
			'Echoing the stories told in his book, this field grew through a dialogue between physical observation and mathematical imagination.'
		],
		visualLabel: 'Transition motif from Stanza I'
	},
	{
		id: 'euler-question',
		title: 'Connecting two rings',
		body: [
			"In the 1740's, Leonhard Euler worked on a deceptively simple question:",
			'> What surface of revolution connects two rings using the least possible area?',
			'A natural starting point would be rotating a straight line around the rings to make a cylinder.'
		],
		stages: [
			{
				prompt: 'But we can do better if we cinch the middle.',
				caption: 'Drag the point up and down.'
			},
			{
				prompt: 'What if the transition were smooth instead of sharp?',
				caption: 'Drag the second point sideways to soften the curve.'
			},
			{
				prompt:
					"In 1744, Leonhard Euler identified the optimal curve that produces the smallest possible surface.",
				caption: 'The optimal curve.'
			}
		]
		// Visual: the live catenoid interactive, rendered directly by this page.
	},
	{
		id: 'euler-answer',
		title: 'The Catenoid',
		body: [
			'Euler proved the optimal surface comes from rotating a familiar curve.',
			'The curve is called the **catenary**, from the Latin *catena* ("chain"), because it is the shape naturally formed by a freely hanging chain.',
			'Euler called the shape generated by rotating it the **catenoid**, which turned out to be the first identified minimal surface (other than a plane).'
		],
		visualLabel: 'Chain animation'
	},
	{
		id: 'defining-property',
		title: 'The special curvature of the Catenoid',
		// `stages` replaces `body` for this slide — each prompt is shown in
		// the sticky panel in turn as the reader scrolls through
		// MeanCurvatureScene's own five animation beats (see
		// MEAN_CURVATURE_STAGES / curvatureStageIndex in +page.svelte),
		// rather than sitting as one static block for the whole animation.
		stages: [
			{ prompt: "In the decades that followed, it was proven that the catenoid has a very interesting property. Let's zoom into a single point on its surface." },
			{ prompt: 'Around the point on top of the catenoid, there are two curves that reveal how the surface bends -- one bends along the **catenary curve**, and the other around the **rotational curve**.' },
			{ prompt: 'Isolated from the surface, we can see two curves bend in opposite directions.' },
			{ prompt: 'Rotating the curves lets us see that these principal curves on the surface around this point...' },
			{ prompt: '... have the exact same amount of curvature, but in opposite directions. This feature, defined as a **mean curvature of zero** is true not just at this point, but at all points on the surface of the catenoid... And more strikingly **at all points of every smooth minimal surface**.' }
		]
		// Visual: MeanCurvatureScene, rendered directly by this page (see
		// the scene-panel branch for curvatureIndex in +page.svelte).
	},
	{
		id: 'soap-film',
		title: 'Nature mimics math mimics nature',
		body: [
			//////////// CHECK FOR EDITS IN CHATGPT CHAT ////////////////
			'Minimal surfaces are **mathematical objects**.',
			"But researchers has often used **natural models**, specifically soal films, to explore them.", 
			"It was known in the 1700's that soap films, following the laws of surface tension, created minimal surfaces. But it wasn't until the 1840's, a hundred years after Euler's proof, that physicist Joseph Plateau developed a stable enough soap film mixture to systematically reseaarch how they form around wire frames.",
			'By pulling apart two rings dipped in soap, he made the first known stable catenoid Euler described a century before.',
		],
		visualLabel: 'Soap-film visualization'
	},
	{
		id: 'field-grows',
		title: 'An explosion of surfaces',
		body: [
			//////////// CHECK FOR EDITS IN CHATGPT CHAT ////////////////
			'While the stabilization of the catenoid took material inventiveness, mathematical ingenuity was required in the hundred year path towards describing an infinite range of surfaces.' ,
			"In the 1760's Joseph-Louis de Lagrange provided the exact equation that any 2 dimensional minimal surface must... Unfortunately the equations were essentially unsolvable.",
			"It wasn't until 1860's that Weierstrass, Enneper and Riemann derived a simplification that changed that. Using complex numbers (the sum of a real and imaginary number) they developed a way to define an infinite family of minimal surfaces.",
			'This new approach helped transform isolated examples into a coherent field of geometry.',
			'Choose a minimal surface family, and tweak the parameters of the functions to see the minimal surfaces they describe.'
		],
		visualLabel: 'Gallery of minimal surfaces (Riemann’s family)'
	}, 
	/*
	{
		id: 'field-grows',
		title: 'An explosion of surfaces',
		body: [
			'Over the following century, mathematicians continue to study these surfaces, but defining new surfaces was hampered by needing solving an impractically different set of equations.',
			"Weierstrass, building on Riemann's methods changed that. Using complex numbers (the sum of a real and imaginary number) they developed a way to define an infinite family of minimal surfaces.",
			'This new approach helped transform isolated examples into a coherent field of geometry.'
		],
		visualLabel: 'Gallery of minimal surfaces (Riemann’s family)'
	},*/ 
	{
		id: 'two-centuries',
		title: 'The Field Keeps Growing',
		body: [
			'Throughout the nineteenth and twentieth centuries, mathematicians discovered new minimal surfaces, developed general methods for constructing and classifying them, and explored when they exist and when they remain stable.',
			'By 1969, enough of that work had accumulated for Robert Osserman to bring much of the subject together in a graduate-level textbook: *A Survey of Minimal Surfaces*.',
			'Just one year later, NASA researcher Alan Schoen described a remarkable new family of **triply periodic minimal surfaces**, including the **gyroid**. Developed within an engineering research environment, these surfaces would later become some of the most influential geometries outside mathematics.',
			'Using the citations of this textbook, the next stanza follows that journey of minimal surfaces from 200 years of theoretical math to applications in fields ranging from materials science and biology to computer graphics, computer vision and theoretical physics.'
		]
		// This is now the outro (see .cover-section in +page.svelte) — no
		// visualLabel, it doesn't sit in the scene-panel flow the slides
		// before it use.
	},
/*	{
		id: 'transition',
		title: 'Beyond Mathematics',
		body: [
			'For more than two centuries, minimal surfaces grew primarily as a branch of pure mathematics.',
			'Then researchers in fields ranging from materials science and biology to computer graphics, computer vision and theoretical physics began recognizing these same geometries in their own work.',
			'The next stanza follows that journey through the citation history of *A Survey of Minimal Surfaces*.'
		],
		visualLabel: 'Preview of the citation network (Stanza III)'
	}*/
];
